id: DA4406A0C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-02-24T10:23:53+00:00'
last_modified: '2022-05-26T10:26:24.328844+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    6ab6:
      image_group_id: I1PD95863
      title: རྣལ་འབྱོར་ཆེན་པོའི་རྒྱུད་དཔལ་གསང་བ་འདུས་པའི་གཏོར་མའི་ཆོ་ག
      total_pages: 1634
      order: 18
      base_file: 6ab6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
